// <auto-generated />
using System;
using AuthService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Models.AppModels.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CaloriesPer100g")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("DefaultUnitId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Density")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Fats")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("Fibers")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("GramsPerUnit")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("IngredientUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Proteins")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("Sodium")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientUnitId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CaloriesPer100g = 250.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 20.00m,
                            Fibers = 0.00m,
                            Name = "Beef",
                            Proteins = 26.00m,
                            Sodium = 0.05m
                        },
                        new
                        {
                            Id = 102,
                            CaloriesPer100g = 165.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 3.60m,
                            Fibers = 0.00m,
                            Name = "Chicken breast",
                            Proteins = 31.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 103,
                            CaloriesPer100g = 209.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 11.00m,
                            Fibers = 0.00m,
                            Name = "Chicken thighs",
                            Proteins = 26.00m,
                            Sodium = 0.08m
                        },
                        new
                        {
                            Id = 104,
                            CaloriesPer100g = 172.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 6.00m,
                            Fibers = 0.00m,
                            Name = "Chicken drumsticks",
                            Proteins = 28.00m,
                            Sodium = 0.09m
                        },
                        new
                        {
                            Id = 105,
                            CaloriesPer100g = 143.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 3.00m,
                            Fibers = 0.00m,
                            Name = "Goat meat",
                            Proteins = 27.00m,
                            Sodium = 0.08m
                        },
                        new
                        {
                            Id = 106,
                            CaloriesPer100g = 242.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 14.00m,
                            Fibers = 0.00m,
                            Name = "Pork",
                            Proteins = 27.00m,
                            Sodium = 0.06m
                        },
                        new
                        {
                            Id = 107,
                            CaloriesPer100g = 321.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 28.00m,
                            Fibers = 0.00m,
                            Name = "Pork ribs",
                            Proteins = 16.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 108,
                            CaloriesPer100g = 135.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 1.00m,
                            Fibers = 0.00m,
                            Name = "Turkey",
                            Proteins = 29.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 109,
                            CaloriesPer100g = 337.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 28.00m,
                            Fibers = 0.00m,
                            Name = "Duck",
                            Proteins = 19.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 110,
                            CaloriesPer100g = 136.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 3.50m,
                            Fibers = 0.00m,
                            Name = "Rabbit",
                            Proteins = 25.00m,
                            Sodium = 0.05m
                        },
                        new
                        {
                            Id = 111,
                            CaloriesPer100g = 258.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 17.00m,
                            Fibers = 0.00m,
                            Name = "Lamb",
                            Proteins = 25.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 112,
                            CaloriesPer100g = 135.00m,
                            Carbohydrates = 4.00m,
                            DefaultUnitId = 1,
                            Fats = 3.60m,
                            Fibers = 0.00m,
                            Name = "Beef liver",
                            Proteins = 20.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 113,
                            CaloriesPer100g = 119.00m,
                            Carbohydrates = 1.00m,
                            DefaultUnitId = 1,
                            Fats = 5.00m,
                            Fibers = 0.00m,
                            Name = "Chicken liver",
                            Proteins = 17.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 114,
                            CaloriesPer100g = 85.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 3.70m,
                            Fibers = 0.00m,
                            Name = "Beef tripe",
                            Proteins = 12.00m,
                            Sodium = 0.06m
                        },
                        new
                        {
                            Id = 115,
                            CaloriesPer100g = 290.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 19.00m,
                            Fibers = 0.00m,
                            Name = "Smoked beef",
                            Proteins = 28.00m,
                            Sodium = 1.20m
                        },
                        new
                        {
                            Id = 116,
                            CaloriesPer100g = 128.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 2.70m,
                            Fibers = 0.00m,
                            Name = "Fresh fish (tilapia)",
                            Proteins = 26.00m,
                            Sodium = 0.06m
                        },
                        new
                        {
                            Id = 117,
                            CaloriesPer100g = 205.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 14.00m,
                            Fibers = 0.00m,
                            Name = "Mackerel (maquereau)",
                            Proteins = 19.00m,
                            Sodium = 0.08m
                        },
                        new
                        {
                            Id = 118,
                            CaloriesPer100g = 162.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 9.00m,
                            Fibers = 0.00m,
                            Name = "Catfish (poisson-chat)",
                            Proteins = 18.00m,
                            Sodium = 0.06m
                        },
                        new
                        {
                            Id = 119,
                            CaloriesPer100g = 150.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 6.00m,
                            Fibers = 0.00m,
                            Name = "Croaker (corb)",
                            Proteins = 22.00m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 120,
                            CaloriesPer100g = 175.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 8.00m,
                            Fibers = 0.00m,
                            Name = "Barracuda",
                            Proteins = 24.00m,
                            Sodium = 0.08m
                        },
                        new
                        {
                            Id = 121,
                            CaloriesPer100g = 158.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 8.00m,
                            Fibers = 0.00m,
                            Name = "Bonga fish (poisson bonga)",
                            Proteins = 21.00m,
                            Sodium = 0.09m
                        },
                        new
                        {
                            Id = 122,
                            CaloriesPer100g = 208.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 11.00m,
                            Fibers = 0.00m,
                            Name = "Sardines",
                            Proteins = 25.00m,
                            Sodium = 0.05m
                        },
                        new
                        {
                            Id = 123,
                            CaloriesPer100g = 184.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 6.00m,
                            Fibers = 0.00m,
                            Name = "Tuna",
                            Proteins = 30.00m,
                            Sodium = 0.05m
                        },
                        new
                        {
                            Id = 124,
                            CaloriesPer100g = 128.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 2.00m,
                            Fibers = 0.00m,
                            Name = "Snapper (vivaneau)",
                            Proteins = 26.00m,
                            Sodium = 0.06m
                        },
                        new
                        {
                            Id = 125,
                            CaloriesPer100g = 190.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 8.00m,
                            Fibers = 0.00m,
                            Name = "Smoked fish",
                            Proteins = 28.00m,
                            Sodium = 1.50m
                        },
                        new
                        {
                            Id = 126,
                            CaloriesPer100g = 280.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 8.00m,
                            Fibers = 0.00m,
                            Name = "Dried fish",
                            Proteins = 50.00m,
                            Sodium = 2.00m
                        },
                        new
                        {
                            Id = 127,
                            CaloriesPer100g = 85.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 0.50m,
                            Fibers = 0.00m,
                            GramsPerUnit = 10.00m,
                            Name = "Shrimp (fresh)",
                            Proteins = 20.00m,
                            Sodium = 0.30m
                        },
                        new
                        {
                            Id = 128,
                            CaloriesPer100g = 250.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 5.00m,
                            Fibers = 0.00m,
                            GramsPerUnit = 2.00m,
                            Name = "Dried shrimp",
                            Proteins = 50.00m,
                            Sodium = 2.50m
                        },
                        new
                        {
                            Id = 129,
                            CaloriesPer100g = 87.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 1.50m,
                            Fibers = 0.00m,
                            Name = "Crab",
                            Proteins = 18.00m,
                            Sodium = 0.30m
                        },
                        new
                        {
                            Id = 130,
                            CaloriesPer100g = 110.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 1,
                            Fats = 2.00m,
                            Fibers = 0.00m,
                            GramsPerUnit = 5.00m,
                            Name = "Crayfish",
                            Proteins = 22.00m,
                            Sodium = 0.20m
                        },
                        new
                        {
                            Id = 131,
                            CaloriesPer100g = 45.00m,
                            Carbohydrates = 5.00m,
                            DefaultUnitId = 1,
                            Fats = 1.00m,
                            Fibers = 4.00m,
                            Name = "Ndolé leaves (bitter leaf)",
                            Proteins = 4.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 132,
                            CaloriesPer100g = 50.00m,
                            Carbohydrates = 6.00m,
                            DefaultUnitId = 1,
                            Fats = 1.50m,
                            Fibers = 3.00m,
                            Name = "Eru leaves",
                            Proteins = 4.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 133,
                            CaloriesPer100g = 33.00m,
                            Carbohydrates = 7.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 3.20m,
                            GramsPerUnit = 15.00m,
                            Name = "Okra (gombo)",
                            Proteins = 2.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 134,
                            CaloriesPer100g = 23.00m,
                            Carbohydrates = 3.00m,
                            DefaultUnitId = 1,
                            Fats = 0.40m,
                            Fibers = 1.50m,
                            Name = "Waterleaf",
                            Proteins = 2.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 135,
                            CaloriesPer100g = 42.00m,
                            Carbohydrates = 5.00m,
                            DefaultUnitId = 1,
                            Fats = 0.80m,
                            Fibers = 3.50m,
                            Name = "Huckleberry leaves (folong)",
                            Proteins = 4.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 136,
                            CaloriesPer100g = 91.00m,
                            Carbohydrates = 13.00m,
                            DefaultUnitId = 1,
                            Fats = 2.00m,
                            Fibers = 5.00m,
                            Name = "Cassava leaves",
                            Proteins = 7.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 137,
                            CaloriesPer100g = 32.00m,
                            Carbohydrates = 5.00m,
                            DefaultUnitId = 1,
                            Fats = 0.40m,
                            Fibers = 2.50m,
                            Name = "Pumpkin leaves",
                            Proteins = 3.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 138,
                            CaloriesPer100g = 23.00m,
                            Carbohydrates = 3.60m,
                            DefaultUnitId = 1,
                            Fats = 0.40m,
                            Fibers = 2.20m,
                            Name = "Spinach",
                            Proteins = 2.90m,
                            Sodium = 0.08m
                        },
                        new
                        {
                            Id = 139,
                            CaloriesPer100g = 25.00m,
                            Carbohydrates = 5.80m,
                            DefaultUnitId = 1,
                            Fats = 0.10m,
                            Fibers = 2.50m,
                            Name = "Cabbage",
                            Proteins = 1.30m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 140,
                            CaloriesPer100g = 15.00m,
                            Carbohydrates = 2.90m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 1.30m,
                            Name = "Lettuce",
                            Proteins = 1.40m,
                            Sodium = 0.03m
                        },
                        new
                        {
                            Id = 141,
                            CaloriesPer100g = 41.00m,
                            Carbohydrates = 9.60m,
                            DefaultUnitId = 10,
                            Fats = 0.20m,
                            Fibers = 2.80m,
                            GramsPerUnit = 60.00m,
                            Name = "Carrot",
                            Proteins = 0.90m,
                            Sodium = 0.07m
                        },
                        new
                        {
                            Id = 142,
                            CaloriesPer100g = 20.00m,
                            Carbohydrates = 4.60m,
                            DefaultUnitId = 10,
                            Fats = 0.20m,
                            Fibers = 1.70m,
                            GramsPerUnit = 120.00m,
                            Name = "Green bell pepper",
                            Proteins = 0.90m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 143,
                            CaloriesPer100g = 31.00m,
                            Carbohydrates = 6.00m,
                            DefaultUnitId = 10,
                            Fats = 0.30m,
                            Fibers = 2.10m,
                            GramsPerUnit = 120.00m,
                            Name = "Red bell pepper",
                            Proteins = 1.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 144,
                            CaloriesPer100g = 40.00m,
                            Carbohydrates = 8.80m,
                            DefaultUnitId = 13,
                            Fats = 0.40m,
                            Fibers = 1.50m,
                            GramsPerUnit = 10.00m,
                            Name = "Hot pepper (piment)",
                            Proteins = 1.90m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 145,
                            CaloriesPer100g = 25.00m,
                            Carbohydrates = 5.70m,
                            DefaultUnitId = 10,
                            Fats = 0.20m,
                            Fibers = 3.00m,
                            GramsPerUnit = 80.00m,
                            Name = "African eggplant (aubergine)",
                            Proteins = 1.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 146,
                            CaloriesPer100g = 17.00m,
                            Carbohydrates = 3.10m,
                            DefaultUnitId = 10,
                            Fats = 0.30m,
                            Fibers = 1.00m,
                            GramsPerUnit = 200.00m,
                            Name = "Zucchini",
                            Proteins = 1.20m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 147,
                            CaloriesPer100g = 31.00m,
                            Carbohydrates = 7.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 3.40m,
                            Name = "Green beans",
                            Proteins = 1.80m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 148,
                            CaloriesPer100g = 81.00m,
                            Carbohydrates = 14.40m,
                            DefaultUnitId = 1,
                            Fats = 0.40m,
                            Fibers = 5.00m,
                            Name = "Peas",
                            Proteins = 5.40m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 149,
                            CaloriesPer100g = 86.00m,
                            Carbohydrates = 19.00m,
                            DefaultUnitId = 10,
                            Fats = 1.20m,
                            Fibers = 2.70m,
                            GramsPerUnit = 150.00m,
                            Name = "Corn (maize)",
                            Proteins = 3.20m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 150,
                            CaloriesPer100g = 22.00m,
                            Carbohydrates = 3.30m,
                            DefaultUnitId = 1,
                            Fats = 0.30m,
                            Fibers = 1.00m,
                            Name = "Mushrooms",
                            Proteins = 3.10m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 151,
                            CaloriesPer100g = 160.00m,
                            Carbohydrates = 38.00m,
                            DefaultUnitId = 1,
                            Fats = 0.30m,
                            Fibers = 1.80m,
                            Name = "Cassava (fresh)",
                            Proteins = 1.40m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 152,
                            CaloriesPer100g = 150.00m,
                            Carbohydrates = 36.00m,
                            DefaultUnitId = 1,
                            Fats = 0.30m,
                            Fibers = 1.70m,
                            Name = "Cassava (frozen)",
                            Proteins = 1.30m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 153,
                            CaloriesPer100g = 118.00m,
                            Carbohydrates = 28.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 4.10m,
                            Name = "Yam",
                            Proteins = 1.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 154,
                            CaloriesPer100g = 86.00m,
                            Carbohydrates = 20.00m,
                            DefaultUnitId = 10,
                            Fats = 0.10m,
                            Fibers = 3.00m,
                            GramsPerUnit = 150.00m,
                            Name = "Sweet potato (orange)",
                            Proteins = 1.60m,
                            Sodium = 0.06m
                        },
                        new
                        {
                            Id = 155,
                            CaloriesPer100g = 90.00m,
                            Carbohydrates = 21.00m,
                            DefaultUnitId = 10,
                            Fats = 0.10m,
                            Fibers = 2.50m,
                            GramsPerUnit = 150.00m,
                            Name = "Sweet potato (white)",
                            Proteins = 1.60m,
                            Sodium = 0.06m
                        },
                        new
                        {
                            Id = 156,
                            CaloriesPer100g = 112.00m,
                            Carbohydrates = 26.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 2.50m,
                            Name = "Cocoyam (macabo)",
                            Proteins = 1.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 157,
                            CaloriesPer100g = 112.00m,
                            Carbohydrates = 26.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 4.00m,
                            Name = "Taro (pomme de terre)",
                            Proteins = 1.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 158,
                            CaloriesPer100g = 77.00m,
                            Carbohydrates = 17.00m,
                            DefaultUnitId = 10,
                            Fats = 0.10m,
                            Fibers = 2.20m,
                            GramsPerUnit = 150.00m,
                            Name = "Potato (Irish potato)",
                            Proteins = 2.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 159,
                            CaloriesPer100g = 116.00m,
                            Carbohydrates = 31.00m,
                            DefaultUnitId = 10,
                            Fats = 0.40m,
                            Fibers = 2.30m,
                            GramsPerUnit = 200.00m,
                            Name = "Plantain (green/unripe)",
                            Proteins = 1.20m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 160,
                            CaloriesPer100g = 122.00m,
                            Carbohydrates = 32.00m,
                            DefaultUnitId = 10,
                            Fats = 0.40m,
                            Fibers = 2.30m,
                            GramsPerUnit = 200.00m,
                            Name = "Plantain (ripe/yellow)",
                            Proteins = 1.30m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 161,
                            CaloriesPer100g = 130.00m,
                            Carbohydrates = 34.00m,
                            DefaultUnitId = 10,
                            Fats = 0.40m,
                            Fibers = 2.00m,
                            GramsPerUnit = 200.00m,
                            Name = "Plantain (very ripe/black)",
                            Proteins = 1.30m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 162,
                            CaloriesPer100g = 89.00m,
                            Carbohydrates = 22.80m,
                            DefaultUnitId = 10,
                            Fats = 0.30m,
                            Fibers = 2.60m,
                            GramsPerUnit = 120.00m,
                            Name = "Banana (dessert)",
                            Proteins = 1.10m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 163,
                            CaloriesPer100g = 350.00m,
                            Carbohydrates = 80.00m,
                            DefaultUnitId = 1,
                            Fats = 1.00m,
                            Fibers = 2.00m,
                            Name = "Fufu flour (corn)",
                            Proteins = 3.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 164,
                            CaloriesPer100g = 360.00m,
                            Carbohydrates = 88.00m,
                            DefaultUnitId = 1,
                            Fats = 0.50m,
                            Fibers = 2.00m,
                            Name = "Fufu flour (cassava)",
                            Proteins = 1.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 165,
                            CaloriesPer100g = 350.00m,
                            Carbohydrates = 85.00m,
                            DefaultUnitId = 1,
                            Fats = 0.50m,
                            Fibers = 3.00m,
                            Name = "Garri (cassava granules)",
                            Proteins = 1.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 166,
                            CaloriesPer100g = 60.00m,
                            Carbohydrates = 15.00m,
                            DefaultUnitId = 10,
                            Fats = 0.40m,
                            Fibers = 1.60m,
                            GramsPerUnit = 200.00m,
                            Name = "Mango",
                            Proteins = 0.80m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 167,
                            CaloriesPer100g = 50.00m,
                            Carbohydrates = 13.00m,
                            DefaultUnitId = 1,
                            Fats = 0.10m,
                            Fibers = 1.40m,
                            Name = "Pineapple",
                            Proteins = 0.50m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 168,
                            CaloriesPer100g = 43.00m,
                            Carbohydrates = 11.00m,
                            DefaultUnitId = 1,
                            Fats = 0.30m,
                            Fibers = 1.70m,
                            Name = "Papaya",
                            Proteins = 0.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 169,
                            CaloriesPer100g = 160.00m,
                            Carbohydrates = 8.50m,
                            DefaultUnitId = 10,
                            Fats = 15.00m,
                            Fibers = 6.70m,
                            GramsPerUnit = 150.00m,
                            Name = "Avocado",
                            Proteins = 2.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 170,
                            CaloriesPer100g = 47.00m,
                            Carbohydrates = 12.00m,
                            DefaultUnitId = 10,
                            Fats = 0.10m,
                            Fibers = 2.40m,
                            GramsPerUnit = 130.00m,
                            Name = "Orange",
                            Proteins = 0.90m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 171,
                            CaloriesPer100g = 53.00m,
                            Carbohydrates = 13.00m,
                            DefaultUnitId = 10,
                            Fats = 0.30m,
                            Fibers = 1.80m,
                            GramsPerUnit = 80.00m,
                            Name = "Tangerine",
                            Proteins = 0.80m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 172,
                            CaloriesPer100g = 29.00m,
                            Carbohydrates = 9.00m,
                            DefaultUnitId = 10,
                            Fats = 0.30m,
                            Fibers = 2.80m,
                            GramsPerUnit = 60.00m,
                            Name = "Lemon",
                            Proteins = 1.10m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 173,
                            CaloriesPer100g = 30.00m,
                            Carbohydrates = 11.00m,
                            DefaultUnitId = 10,
                            Fats = 0.20m,
                            Fibers = 2.80m,
                            GramsPerUnit = 50.00m,
                            Name = "Lime",
                            Proteins = 0.70m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 174,
                            CaloriesPer100g = 30.00m,
                            Carbohydrates = 8.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 0.40m,
                            Name = "Watermelon",
                            Proteins = 0.60m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 175,
                            CaloriesPer100g = 34.00m,
                            Carbohydrates = 8.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 0.90m,
                            Name = "Cantaloupe",
                            Proteins = 0.80m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 176,
                            CaloriesPer100g = 68.00m,
                            Carbohydrates = 14.00m,
                            DefaultUnitId = 10,
                            Fats = 1.00m,
                            Fibers = 5.40m,
                            GramsPerUnit = 100.00m,
                            Name = "Guava",
                            Proteins = 2.60m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 177,
                            CaloriesPer100g = 43.00m,
                            Carbohydrates = 11.00m,
                            DefaultUnitId = 1,
                            Fats = 0.30m,
                            Fibers = 1.70m,
                            Name = "Pawpaw",
                            Proteins = 0.50m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 178,
                            CaloriesPer100g = 354.00m,
                            Carbohydrates = 15.00m,
                            DefaultUnitId = 1,
                            Fats = 33.00m,
                            Fibers = 9.00m,
                            Name = "Coconut (fresh meat)",
                            Proteins = 3.30m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 179,
                            CaloriesPer100g = 230.00m,
                            Carbohydrates = 5.50m,
                            DefaultUnitId = 4,
                            Density = 1.03m,
                            Fats = 24.00m,
                            Fibers = 0.00m,
                            Name = "Coconut milk",
                            Proteins = 2.30m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 180,
                            CaloriesPer100g = 260.00m,
                            Carbohydrates = 14.00m,
                            DefaultUnitId = 1,
                            Fats = 22.00m,
                            Fibers = 8.00m,
                            Name = "Palm fruit",
                            Proteins = 2.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 181,
                            CaloriesPer100g = 130.00m,
                            Carbohydrates = 28.00m,
                            DefaultUnitId = 1,
                            Fats = 0.30m,
                            Fibers = 0.40m,
                            Name = "Rice (white)",
                            Proteins = 2.70m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 182,
                            CaloriesPer100g = 123.00m,
                            Carbohydrates = 25.00m,
                            DefaultUnitId = 1,
                            Fats = 0.90m,
                            Fibers = 1.80m,
                            Name = "Rice (brown)",
                            Proteins = 2.70m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 183,
                            CaloriesPer100g = 132.00m,
                            Carbohydrates = 23.00m,
                            DefaultUnitId = 1,
                            Fats = 0.50m,
                            Fibers = 7.00m,
                            Name = "Beans (black)",
                            Proteins = 8.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 184,
                            CaloriesPer100g = 139.00m,
                            Carbohydrates = 25.00m,
                            DefaultUnitId = 1,
                            Fats = 0.50m,
                            Fibers = 6.00m,
                            Name = "Beans (red)",
                            Proteins = 8.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 185,
                            CaloriesPer100g = 116.00m,
                            Carbohydrates = 20.00m,
                            DefaultUnitId = 1,
                            Fats = 0.50m,
                            Fibers = 6.00m,
                            Name = "Cowpeas (niébé)",
                            Proteins = 8.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 186,
                            CaloriesPer100g = 567.00m,
                            Carbohydrates = 16.10m,
                            DefaultUnitId = 1,
                            Fats = 49.20m,
                            Fibers = 8.50m,
                            Name = "Groundnuts (peanuts) - raw",
                            Proteins = 25.80m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 187,
                            CaloriesPer100g = 587.00m,
                            Carbohydrates = 21.00m,
                            DefaultUnitId = 1,
                            Fats = 50.00m,
                            Fibers = 9.00m,
                            Name = "Ground peanuts (roasted)",
                            Proteins = 24.00m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 188,
                            CaloriesPer100g = 598.00m,
                            Carbohydrates = 22.00m,
                            DefaultUnitId = 6,
                            Density = 1.10m,
                            Fats = 51.00m,
                            Fibers = 5.00m,
                            Name = "Peanut butter",
                            Proteins = 22.00m,
                            Sodium = 0.50m
                        },
                        new
                        {
                            Id = 189,
                            CaloriesPer100g = 361.00m,
                            Carbohydrates = 76.00m,
                            DefaultUnitId = 1,
                            Fats = 1.50m,
                            Fibers = 7.00m,
                            Name = "Cornmeal",
                            Proteins = 7.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 190,
                            CaloriesPer100g = 378.00m,
                            Carbohydrates = 73.00m,
                            DefaultUnitId = 1,
                            Fats = 4.20m,
                            Fibers = 8.50m,
                            Name = "Millet",
                            Proteins = 11.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 191,
                            CaloriesPer100g = 339.00m,
                            Carbohydrates = 74.00m,
                            DefaultUnitId = 1,
                            Fats = 3.30m,
                            Fibers = 6.70m,
                            Name = "Sorghum",
                            Proteins = 11.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 192,
                            CaloriesPer100g = 364.00m,
                            Carbohydrates = 76.00m,
                            DefaultUnitId = 1,
                            Fats = 1.00m,
                            Fibers = 2.70m,
                            Name = "Wheat flour",
                            Proteins = 10.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 193,
                            CaloriesPer100g = 265.00m,
                            Carbohydrates = 49.00m,
                            DefaultUnitId = 1,
                            Fats = 3.20m,
                            Fibers = 2.50m,
                            Name = "Bread",
                            Proteins = 9.00m,
                            Sodium = 0.50m
                        },
                        new
                        {
                            Id = 194,
                            CaloriesPer100g = 131.00m,
                            Carbohydrates = 25.00m,
                            DefaultUnitId = 1,
                            Fats = 1.10m,
                            Fibers = 1.80m,
                            Name = "Pasta",
                            Proteins = 5.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 195,
                            CaloriesPer100g = 103.00m,
                            Carbohydrates = 27.00m,
                            DefaultUnitId = 1,
                            Fats = 0.20m,
                            Fibers = 4.90m,
                            Name = "Breadfruit",
                            Proteins = 1.10m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 196,
                            CaloriesPer100g = 884.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 6,
                            Density = 0.92m,
                            Fats = 100.00m,
                            Fibers = 0.00m,
                            Name = "Palm oil (red)",
                            Proteins = 0.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 197,
                            CaloriesPer100g = 884.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 6,
                            Density = 0.92m,
                            Fats = 100.00m,
                            Fibers = 0.00m,
                            Name = "Vegetable oil",
                            Proteins = 0.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 198,
                            CaloriesPer100g = 884.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 6,
                            Density = 0.92m,
                            Fats = 100.00m,
                            Fibers = 0.00m,
                            Name = "Olive oil",
                            Proteins = 0.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 199,
                            CaloriesPer100g = 884.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 6,
                            Density = 0.92m,
                            Fats = 100.00m,
                            Fibers = 0.00m,
                            Name = "Groundnut oil",
                            Proteins = 0.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 200,
                            CaloriesPer100g = 717.00m,
                            Carbohydrates = 0.10m,
                            DefaultUnitId = 6,
                            Density = 0.91m,
                            Fats = 81.00m,
                            Fibers = 0.00m,
                            Name = "Butter",
                            Proteins = 0.90m,
                            Sodium = 0.50m
                        },
                        new
                        {
                            Id = 201,
                            CaloriesPer100g = 717.00m,
                            Carbohydrates = 0.20m,
                            DefaultUnitId = 6,
                            Density = 0.91m,
                            Fats = 81.00m,
                            Fibers = 0.00m,
                            Name = "Margarine",
                            Proteins = 0.20m,
                            Sodium = 0.80m
                        },
                        new
                        {
                            Id = 202,
                            CaloriesPer100g = 724.00m,
                            Carbohydrates = 0.60m,
                            DefaultUnitId = 6,
                            Density = 0.92m,
                            Fats = 79.00m,
                            Fibers = 0.00m,
                            Name = "Mayonnaise",
                            Proteins = 1.00m,
                            Sodium = 0.50m
                        },
                        new
                        {
                            Id = 203,
                            CaloriesPer100g = 884.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 6,
                            Density = 0.92m,
                            Fats = 100.00m,
                            Fibers = 0.00m,
                            Name = "Palm kernel oil",
                            Proteins = 0.00m,
                            Sodium = 0.00m
                        },
                        new
                        {
                            Id = 204,
                            CaloriesPer100g = 0.00m,
                            Carbohydrates = 0.00m,
                            DefaultUnitId = 7,
                            Density = 1.20m,
                            Fats = 0.00m,
                            Fibers = 0.00m,
                            Name = "Salt",
                            Proteins = 0.00m,
                            Sodium = 38.76m
                        },
                        new
                        {
                            Id = 205,
                            CaloriesPer100g = 255.00m,
                            Carbohydrates = 50.00m,
                            DefaultUnitId = 7,
                            Density = 0.50m,
                            Fats = 3.00m,
                            Fibers = 25.00m,
                            GramsPerUnit = 2.00m,
                            Name = "Black pepper",
                            Proteins = 10.00m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 206,
                            CaloriesPer100g = 255.00m,
                            Carbohydrates = 50.00m,
                            DefaultUnitId = 7,
                            Density = 0.50m,
                            Fats = 2.00m,
                            Fibers = 25.00m,
                            GramsPerUnit = 2.00m,
                            Name = "White pepper",
                            Proteins = 10.00m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 207,
                            CaloriesPer100g = 200.00m,
                            Carbohydrates = 15.00m,
                            DefaultUnitId = 9,
                            Fats = 12.00m,
                            Fibers = 0.00m,
                            GramsPerUnit = 10.00m,
                            Name = "Maggi cube",
                            Proteins = 8.00m,
                            Sodium = 15.00m
                        },
                        new
                        {
                            Id = 208,
                            CaloriesPer100g = 341.00m,
                            Carbohydrates = 79.00m,
                            DefaultUnitId = 7,
                            Density = 0.40m,
                            Fats = 1.00m,
                            Fibers = 9.00m,
                            GramsPerUnit = 2.00m,
                            Name = "Onion powder",
                            Proteins = 10.00m,
                            Sodium = 0.05m
                        },
                        new
                        {
                            Id = 209,
                            CaloriesPer100g = 331.00m,
                            Carbohydrates = 72.00m,
                            DefaultUnitId = 7,
                            Density = 0.40m,
                            Fats = 0.70m,
                            Fibers = 9.00m,
                            GramsPerUnit = 2.00m,
                            Name = "Garlic powder",
                            Proteins = 16.00m,
                            Sodium = 0.05m
                        },
                        new
                        {
                            Id = 210,
                            CaloriesPer100g = 80.00m,
                            Carbohydrates = 18.00m,
                            DefaultUnitId = 1,
                            Fats = 0.80m,
                            Fibers = 2.00m,
                            GramsPerUnit = 10.00m,
                            Name = "Ginger (fresh)",
                            Proteins = 1.80m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 211,
                            CaloriesPer100g = 335.00m,
                            Carbohydrates = 71.00m,
                            DefaultUnitId = 7,
                            Density = 0.40m,
                            Fats = 4.00m,
                            Fibers = 14.00m,
                            GramsPerUnit = 2.00m,
                            Name = "Ginger powder",
                            Proteins = 9.00m,
                            Sodium = 0.03m
                        },
                        new
                        {
                            Id = 212,
                            CaloriesPer100g = 276.00m,
                            Carbohydrates = 63.00m,
                            DefaultUnitId = 7,
                            Density = 0.30m,
                            Fats = 4.00m,
                            Fibers = 37.00m,
                            GramsPerUnit = 1.00m,
                            Name = "Thyme (dried)",
                            Proteins = 9.00m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 213,
                            CaloriesPer100g = 313.00m,
                            Carbohydrates = 75.00m,
                            DefaultUnitId = 7,
                            Density = 0.30m,
                            Fats = 8.00m,
                            Fibers = 26.00m,
                            GramsPerUnit = 1.00m,
                            Name = "Bay leaves",
                            Proteins = 7.60m,
                            Sodium = 0.02m
                        },
                        new
                        {
                            Id = 214,
                            CaloriesPer100g = 557.00m,
                            Carbohydrates = 15.00m,
                            DefaultUnitId = 1,
                            Fats = 47.00m,
                            Fibers = 3.00m,
                            Name = "Egusi seeds (melon seeds)",
                            Proteins = 28.00m,
                            Sodium = 0.03m
                        },
                        new
                        {
                            Id = 215,
                            CaloriesPer100g = 553.00m,
                            Carbohydrates = 30.00m,
                            DefaultUnitId = 1,
                            Fats = 44.00m,
                            Fibers = 3.00m,
                            Name = "Cashew nuts",
                            Proteins = 18.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 216,
                            CaloriesPer100g = 650.00m,
                            Carbohydrates = 15.00m,
                            DefaultUnitId = 1,
                            Fats = 62.00m,
                            Fibers = 8.00m,
                            GramsPerUnit = 5.00m,
                            Name = "African walnut (Coula edulis)",
                            Proteins = 12.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 217,
                            CaloriesPer100g = 620.00m,
                            Carbohydrates = 10.00m,
                            DefaultUnitId = 1,
                            Fats = 55.00m,
                            Fibers = 6.00m,
                            GramsPerUnit = 3.00m,
                            Name = "Conophor nuts (Tetracarpidium)",
                            Proteins = 18.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 218,
                            CaloriesPer100g = 573.00m,
                            Carbohydrates = 23.00m,
                            DefaultUnitId = 1,
                            Fats = 50.00m,
                            Fibers = 12.00m,
                            Name = "Sesame seeds",
                            Proteins = 18.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 219,
                            CaloriesPer100g = 559.00m,
                            Carbohydrates = 10.00m,
                            DefaultUnitId = 1,
                            Fats = 49.00m,
                            Fibers = 6.00m,
                            Name = "Pumpkin seeds",
                            Proteins = 30.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 220,
                            CaloriesPer100g = 584.00m,
                            Carbohydrates = 20.00m,
                            DefaultUnitId = 1,
                            Fats = 51.00m,
                            Fibers = 9.00m,
                            Name = "Sunflower seeds",
                            Proteins = 20.00m,
                            Sodium = 0.01m
                        },
                        new
                        {
                            Id = 221,
                            CaloriesPer100g = 155.00m,
                            Carbohydrates = 1.10m,
                            DefaultUnitId = 9,
                            Fats = 11.00m,
                            Fibers = 0.00m,
                            GramsPerUnit = 50.00m,
                            Name = "Egg (chicken)",
                            Proteins = 13.00m,
                            Sodium = 0.12m
                        },
                        new
                        {
                            Id = 222,
                            CaloriesPer100g = 42.00m,
                            Carbohydrates = 5.00m,
                            DefaultUnitId = 4,
                            Density = 1.03m,
                            Fats = 1.00m,
                            Fibers = 0.00m,
                            Name = "Milk (fresh)",
                            Proteins = 3.40m,
                            Sodium = 0.04m
                        },
                        new
                        {
                            Id = 223,
                            CaloriesPer100g = 496.00m,
                            Carbohydrates = 38.00m,
                            DefaultUnitId = 1,
                            Fats = 27.00m,
                            Fibers = 0.00m,
                            Name = "Milk (powdered)",
                            Proteins = 26.00m,
                            Sodium = 0.40m
                        },
                        new
                        {
                            Id = 224,
                            CaloriesPer100g = 61.00m,
                            Carbohydrates = 4.70m,
                            DefaultUnitId = 1,
                            Fats = 3.30m,
                            Fibers = 0.00m,
                            Name = "Yogurt (plain)",
                            Proteins = 3.50m,
                            Sodium = 0.05m
                        },
                        new
                        {
                            Id = 225,
                            CaloriesPer100g = 300.00m,
                            Carbohydrates = 2.00m,
                            DefaultUnitId = 1,
                            Fats = 24.00m,
                            Fibers = 0.00m,
                            Name = "Cheese (processed)",
                            Proteins = 18.00m,
                            Sodium = 1.50m
                        });
                });

            modelBuilder.Entity("AuthService.Models.AppModels.IngredientUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("IngredientUnits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "g",
                            IsBaseUnit = true,
                            Name = "gram",
                            Type = "weight"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "kg",
                            IsBaseUnit = false,
                            Name = "kilogram",
                            Type = "weight"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "mg",
                            IsBaseUnit = false,
                            Name = "milligram",
                            Type = "weight"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "ml",
                            IsBaseUnit = true,
                            Name = "milliliter",
                            Type = "volume"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "L",
                            IsBaseUnit = false,
                            Name = "liter",
                            Type = "volume"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "tbsp",
                            IsBaseUnit = false,
                            Name = "tablespoon",
                            Type = "volume"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "tsp",
                            IsBaseUnit = false,
                            Name = "teaspoon",
                            Type = "volume"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "cup",
                            IsBaseUnit = false,
                            Name = "cup",
                            Type = "volume"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "pc",
                            IsBaseUnit = true,
                            Name = "piece",
                            Type = "count"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "med",
                            IsBaseUnit = false,
                            Name = "medium",
                            Type = "count"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "lg",
                            IsBaseUnit = false,
                            Name = "large",
                            Type = "count"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "sm",
                            IsBaseUnit = false,
                            Name = "small",
                            Type = "count"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "clove",
                            IsBaseUnit = false,
                            Name = "clove",
                            Type = "count"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "hf",
                            IsBaseUnit = false,
                            Name = "handful",
                            Type = "count"
                        });
                });

            modelBuilder.Entity("AuthService.Models.AppModels.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RegionOfOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("AuthService.Models.AppModels.RecipeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecipeCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional Cameroonian soups and delicacies",
                            Name = "Soups"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Complete meals for lunch and dinner",
                            Name = "Main Dishes"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Morning meals and small chops",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Small bites and street food",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Drinks and smoothies",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("AuthService.Models.AppModels.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("AuthService.Models.AppModels.RecipeInstruction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualInstruction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeInstructions");
                });

            modelBuilder.Entity("AuthService.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "100",
                            AccessFailedCount = 0,
                            Bio = "I am a certified chef that works with tasty foods",
                            ConcurrencyStamp = "fc89f5e4-fb61-4bcf-abfa-bc6548b275da",
                            DateOfBirth = new DateTime(1992, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "wakebeh14@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Wa Kebeh",
                            Gender = "Male",
                            JoinedDate = new DateTime(2026, 3, 4, 21, 1, 6, 93, DateTimeKind.Utc).AddTicks(3625),
                            LastName = "Mbong",
                            Location = "Yaounde",
                            LockoutEnabled = false,
                            NormalizedEmail = "WAKEBEH14@GMAIL.COM",
                            NormalizedUserName = "ADMIN@SYSTEM.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAWa0Ik5LAzKW40falUJRl1fd4USeG1n1s/VBjsLfmtuIKUIaOoA/xkiSL0vejbg6Q==",
                            Phone = "676455676",
                            PhoneNumberConfirmed = false,
                            ProfilePictureUrl = "myphoto.jpg",
                            SecurityStamp = "9c25a0a6-214d-4015-8285-e1e724e8e21a",
                            TwoFactorEnabled = false,
                            UserName = "admin@system.com"
                        });
                });

            modelBuilder.Entity("AuthService.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "100",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AuthService.Models.AppModels.Ingredient", b =>
                {
                    b.HasOne("AuthService.Models.AppModels.IngredientUnit", "IngredientUnit")
                        .WithMany()
                        .HasForeignKey("IngredientUnitId");

                    b.Navigation("IngredientUnit");
                });

            modelBuilder.Entity("AuthService.Models.AppModels.Recipe", b =>
                {
                    b.HasOne("AuthService.Models.AppModels.RecipeCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AuthService.Models.AppModels.RecipeIngredient", b =>
                {
                    b.HasOne("AuthService.Models.AppModels.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Models.AppModels.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Models.AppModels.IngredientUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AuthService.Models.AppModels.RecipeInstruction", b =>
                {
                    b.HasOne("AuthService.Models.AppModels.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("AuthService.Models.RefreshToken", b =>
                {
                    b.HasOne("AuthService.Models.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AuthService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AuthService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AuthService.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthService.Models.AppModels.Recipe", b =>
                {
                    b.Navigation("Instructions");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("AuthService.Models.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
